services:
  my-app:
    build:
      context: .
      args:
        STUDENT_NAME: "Muhammad Affransyah Bayulaksana"
        STUDENT_NIM: "00000077007"
    ports:
      - "80:3000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/use/src/app
    command: "npm run dev"
